### ISSUE TITLE
Not an issue but a request

### ISSUE THREAD

**Issue by wangel** [KaiLoi/update-fw-BC#2]
How hard would it be to change the program to read from a text file?   For example, say I have a text file cidr addresses like:

1.1.1.1/24
2.1.0.0/14
3.4.5.6/18

etc.   Instead of reading the files from ipdeny.com, can I just read the text file instead?   

Thanks!

**Comment by MonolithInd** [comment]
Yea, sure I can probably code this up for you this afternoon. Happy for a text file with an IP per line in the above notation?

**Comment by wangel** [comment]
Yes correct.  Say... I will call my file:  cidr.txt or cidr_list.txt
The file will contain 1 network, per line, just like the .zone files form ipdeny.com, but they will be networks I want to manually put in...

Everything else in the script will work as is.   Basically,  ipdeny.com lists some networks in the wrong zones.  I don't know why.   We ran across one today.   It's listed in the Brazil zone file, but is actually an Azure server in the US ... it's crazy.

It seems that https://www.countryipblocks.net has a more up to date list....  But you can't download them like you can from ipdeny.com.   You can go to their ACL and create a CIDR ACL by highlighting the countries you want blocked.

I was just going to do that, dump them in a .txt file, let your script read them in, aggregate them, and throw them into ipset :)

Thank you!!

**Comment by MonolithInd** [comment]
Done, it works on my server. you just need to specify the filename of your iplist with -l Should work sweet. 

After re-reading some of the code I've been motivated to do a full re-write. Especially if people are actually using it. ;) Need to actually do some error checking on IPs entered and I see some places I could speed it up and also tidy up the code. 

Enjoy!

**Comment by MonolithInd** [comment]
Have implemented the user request.

**Comment by wangel** [comment]
Awesome!  Thank you!!  I will test it out tomorrow at my office.

One thing, how do I download the new version?  It still shows 1.3 on github?

Thanks!

**Comment by MonolithInd** [comment]
opps, my bad.. mashed "git commit" and not "git commit -a" 

Fixed and uploaded

**Comment by wangel** [comment]
Got it!

Testing now.  Thank you sir :)
